### ISSUE TITLE
Add variable to drive use of --replace variable in agent config.sh installation

### ISSUE THREAD

**Issue by TJEvans** [sharegate/ansible-role-azure-devops-agent#1]
Unconfigure agent task is sometime not enough.  Our environment involves VM hosts that are delete/cloned on demand.

**Comment by yohanb** [comment]
Hi @TJEvans ,
I'll look into this!  Shouldn't be too complicated to implement.
Thanks for the interest.

**Comment by yohanb** [comment]
@TJEvans done.  See REAMDE for added variable.
Let me know! ✌
